/* eslint-disable */
/**
 * AUTOGENERATED by scripts/gen-patch-registry.mjs — do not edit by hand.
 *
 * Source of truth: patches/<slug>/patch.json plus the receivers found inside the
 * patch's own .pd files. Run `npm run patches:codegen` after changing either.
 */
import type { AvailableCompositionNames } from "@/components/compositions/compositions-info";
import type { Map3Pd4WebPatch } from "./pd4web-patches";

export const GENERATED_MAP3_PD4WEB_PATCHES = [
  {
    id: "bubble1",
    label: "Bubble 1",
    bundleFolder: "patches/bubble1",
    runtime: "ade2e09dc894",
    activation: {
      moments: ["player"],
      compositions: ["lluvia"],
    },
    channels: {
      receivers: {},
      senders: {},
    },
    tuning: { pollMs: 100, epsilon: 0.0001, accEpsilon: 0.05 },
  },
  {
    id: "exemplo-clima",
    label: "Exemplo: temperatura",
    bundleFolder: "patches/exemplo-clima",
    runtime: "ec746f787802",
    activation: {
      moments: ["player"],
    },
    channels: {
      receivers: {
        "gaia.temp": "gaia.temp",
      },
      senders: {},
    },
    tuning: { pollMs: 100, epsilon: 0.0001, accEpsilon: 0.05 },
  },
  {
    id: "paraisoGaia43",
    label: "Map sound 43",
    bundleFolder: "patches/paraisoGaia43",
    runtime: "f20cb2b1b620",
    activation: {
      moments: ["map","player"],
    },
    channels: {
      receivers: {
        "gaia.acc.x": "aceX",
        "gaia.acc.y": "aceY",
        "gaia.acc.z": "aceZ",
        "gaia.co2": "co2",
        "gaia.lat": "latitude",
        "gaia.lon": "longitude",
        "gaia.sensors": "input",
      },
      senders: {
        "gaia.out": "output",
      },
    },
    tuning: { pollMs: 64, epsilon: 0.5, accEpsilon: 0.05 },
  },
  {
    id: "thunder4",
    label: "Thunder 4",
    bundleFolder: "patches/thunder4",
    runtime: "ade2e09dc894",
    activation: {
      moments: ["player"],
      compositions: ["lightningBolts"],
    },
    channels: {
      receivers: {},
      senders: {},
    },
    tuning: { pollMs: 100, epsilon: 0.0001, accEpsilon: 0.05 },
  },
] as const satisfies readonly Map3Pd4WebPatch[];

/**
 * Which patch plays with which p5 animation.
 *
 * The `satisfies` clause is the guard rail: a composition name that does not
 * exist becomes a tsc error, so a typo in a manifest cannot reach production.
 */
export const COMPOSITION_PATCH_ID = {
  lightningBolts: "thunder4",
  lluvia: "bubble1",
} as const satisfies Partial<
  Record<AvailableCompositionNames, string>
>;

/**
 * The published event contract of each animation. These names belong to the
 * animation, not to any single patch — a new patch for lightningBolts works by
 * listening to [r bolt], with no code change here.
 */
export const COMPOSITION_EVENTS = {
  cloudBubble: {
    emits: [],
    listensTo: [],
  },
  curves: {
    emits: [],
    listensTo: [],
  },
  lightningBolts: {
    emits: ["bolt"],
    listensTo: [],
  },
  lluvia: {
    emits: ["start"],
    listensTo: ["paint"],
  },
} as const;
