import getOpenMeteo from "./getOpenMeteo";

export type FireSpotsResponseData = {
  city: string;
  count: number;
  events: {
    dist: number;
    lat: number;
    lon: number;
  }[];
  state: string;
};

export type RainfallResponseData = {
  city: string;
  clouds: number;
  lat: number;
  lon: number;
  main: {
    feels_like: number;
    grnd_level: number;
    humidity: number;
    pressure: number;
    temp: number;
  };
  rain: { "1h": number } | {};
  state: string;
  visibility: number;
  weather: {
    description: string;
    icon: string;
    main: string;
  }[];
  wind: {
    deg: number;
    gust: number;
    speed: number;
  };
};

export type LightningResponseData = {
  city: string;
  count: number;
  events: { lat: string; lon: string; dist?: number }[];
  state: string;
};

/**
 * Base URL of the satellite backend that serves /fire and /lightning.
 *
 * The deployed stack lives in `satellite-fetcher-aws`. Its API Gateway id is
 * generated by AWS and is specific to the account and region it was deployed
 * into, so it changes on any redeploy elsewhere — which the project needs to do,
 * since the current deployment sits in a personal account belonging to someone
 * who has left. Keeping the id in source meant a code change and a redeploy of
 * the whole site just to point at a different backend.
 *
 * Server-side only, deliberately: every caller of this module is a server
 * component, so the value stays out of the browser bundle. Do not rename this to
 * NEXT_PUBLIC_*.
 *
 * There is no fallback. The literal that used to live here was a migration aid
 * while the variable was being set up; keeping it would have meant the id of the
 * account we are trying to leave stayed in source, which is the whole thing
 * ARQ-01 set out to remove. It is now set in Vercel for every environment, and
 * locally it belongs in .env.local — see .env.example.
 *
 * A missing value does not throw. It reports the source as unavailable, which is
 * the vocabulary BUG-02 established: the callers already handle null, the map
 * popups already say "fonte indisponível", and an unconfigured environment is a
 * source you cannot reach. Throwing would take the whole page down over a
 * configuration mistake, and a page that renders while naming what is missing is
 * easier to diagnose than a stack trace.
 */
function satelliteApiUrl(): string | null {
  const configured = process.env.SATELLITE_API_URL?.trim();
  return configured ? configured.replace(/\/+$/, "") : null;
}

/**
 * The API Gateway key, sent as `x-api-key`.
 *
 * The backend used to answer anyone who asked. It now sits behind a key, a
 * throttle and a monthly quota, because an open endpoint has no ceiling and
 * "inside the free tier" was a hope rather than a property of the system.
 *
 * Safe to hold here: this module only ever runs on the server. The variable
 * carries no NEXT_PUBLIC_ prefix, the calls happen inside Next.js server-side
 * fetches, and the key never reaches a browser.
 *
 * Missing key is not fatal, and deliberately so. It is reported and the request
 * goes out anyway: the request then answers 403 and the caller handles it the
 * same way it handles any unreachable source. Refusing to send would turn a
 * misconfiguration into silence, which is harder to diagnose than a 403 in the
 * logs.
 */
function satelliteHeaders(): HeadersInit | undefined {
  const key = process.env.SATELLITE_API_KEY?.trim();

  if (!key) {
    console.error(
      "[satellite] SATELLITE_API_KEY não está definida — o API Gateway vai " +
        "responder 403. Defina-a no ambiente (Vercel: Settings → Environment " +
        "Variables; local: .env.local). O valor sai de: aws apigateway " +
        "get-api-key --api-key <id> --include-value --query value --output text",
    );
    return undefined;
  }

  return { "x-api-key": key };
}

/**
 * Build the request URL for one of the satellite endpoints.
 *
 * Coordinates are rounded to 2 decimals (~1 km) because they are the cache key.
 * The `revalidate: 7200` below looks like a two-hour cache, but with raw
 * coordinates every pixel of globe movement produced a distinct URL and
 * therefore a fresh request — measured: four renders a few metres apart made
 * four calls each to /fire and /lightning. The endpoints answer for a 100 km
 * radius, so a kilometre of rounding changes nothing about the result while
 * turning "a call per render" into "a call per neighbourhood per two hours".
 *
 * This matters beyond latency: /lightning downloads a NetCDF granule per
 * invocation, and the backend has no throttle or spending ceiling (SEC-01).
 */
function satelliteEndpoint(
  endpoint: string,
  lat: string,
  lon: string,
  dist?: number,
): string | null {
  const base = satelliteApiUrl();
  if (!base) return null;

  const query = new URLSearchParams({
    lat: Number(lat).toFixed(2),
    lon: Number(lon).toFixed(2),
  });
  if (dist !== undefined) query.set("dist", String(dist));
  return `${base}/${endpoint}?${query.toString()}`;
}

/**
 * Fetch one satellite endpoint, returning `null` when the source is unavailable.
 *
 * `null` means "we do not know", and it is deliberately not zero. A backend that
 * is down used to be indistinguishable from a calm sky: this function swallowed
 * every error and returned `undefined` while its signature promised data, so
 * every caller read `.count` off nothing and quietly settled on zero. A real
 * thunderstorm and a broken deploy produced the same silence — which is fatal for
 * a project whose subject is the weather, and worse for any research done on top
 * of it, since the record cannot tell an outage from a quiet night.
 *
 * Returning `null` from a typed signature forces each caller to decide what an
 * unknown means for it. Do not "simplify" this back to `?? 0`.
 */
export default async function getData<T>(
  endpoint: string,
  lat: string,
  lon: string,
  dist?: number,
): Promise<T | null> {
  const url = satelliteEndpoint(endpoint, lat, lon, dist);

  if (!url) {
    console.error(
      `[satellite] ${endpoint} indisponível — SATELLITE_API_URL não está definida. ` +
        "Defina-a no ambiente (Vercel: Settings → Environment Variables; " +
        "local: .env.local) apontando para a base do API Gateway, sem barra final.",
    );
    return null;
  }

  try {
    const res = await fetch(url, {
      headers: satelliteHeaders(),
      next: { revalidate: 7200 },
    });

    if (!res.ok) {
      // The old messages here named satellite-fetcher.up.railway.app, a backend
      // decommissioned in 2023. Reporting a URL that was never called sends
      // whoever is debugging to the wrong place.
      console.error(
        `[satellite] ${endpoint} indisponível — ${url} respondeu ${res.status} ${res.statusText}`,
      );
      return null;
    }

    return (await res.json()) as T;
  } catch (error) {
    console.error(`[satellite] ${endpoint} indisponível — ${url}`, error);
    return null;
  }
}

/** Fire spots near a point, or `null` when NASA FIRMS could not be reached. */
export async function getFireSpots(
  lat: string,
  lon: string,
  dist?: number,
): Promise<FireSpotsResponseData | null> {
  return await getData<FireSpotsResponseData>("fire", lat, lon, dist);
}

export async function getWeather(
  lat: string | number,
  lon: string | number,
  options = { lang: "pt_br" },
): Promise<RainfallResponseData> {
  if (options && options.lang === "en") options.lang = "en_us";
  if (options && options.lang === "pt") options.lang = "pt_br";

  const resp = await getOpenMeteo({ lat, lon });
  return resp;
}

/**
 * Lightning near a point, or `null` when the GOES pipeline could not be reached.
 *
 * This used to answer a failure with `{count: 1, state: "This is mock data..."}`
 * — an invented strike. That branch was in fact unreachable, because getData
 * never threw, so the real behaviour was a silent zero. Both are fabrications;
 * they merely lie in opposite directions. Neither belongs in a system whose
 * output is an artwork about real weather.
 */
export async function getLightning(
  lat: string,
  lon: string,
  dist: number,
): Promise<LightningResponseData | null> {
  return await getData<LightningResponseData>("lightning", lat, lon, dist);
}

export async function reverseGeocode(
  lat: string | number,
  lon: string | number,
): Promise<{
  name: string;
  local_name: any[];
  lat: number;
  lon: number;
  country: string;
  state?: string;
} | null> {
  // Duas mudanças aqui, ambas por motivo próprio.
  //
  // https, não http: a URL carrega a OPEN_WEATHER_API_KEY, e em texto claro ela
  // viaja legível por qualquer intermediário da rede.
  //
  // Coordenada arredondada a 2 casas (~1 km): o nome de um lugar não muda dentro
  // de um quarteirão, mas a coordenada crua muda a cada pixel que o globo se
  // move, e cada valor distinto era uma chamada nova à API. Arredondar é o que
  // transforma "uma chamada por render" em "uma chamada por bairro por dia".
  const cacheKeyLat = Number(lat).toFixed(2);
  const cacheKeyLon = Number(lon).toFixed(2);
  const url = `https://api.openweathermap.org/geo/1.0/reverse?lat=${cacheKeyLat}&lon=${cacheKeyLon}&limit=${1}&appid=${
    process.env.OPEN_WEATHER_API_KEY
  }`;

  try {
    // Nome de lugar é praticamente imutável: 24 h de cache.
    const res = await fetch(url, {
      headers: satelliteHeaders(),
      next: { revalidate: 86400 },
    });
    if (!res.ok) {
      throw new Error(
        `Response from reverse geocode was not ok. Status: ${
          res.status
        } Message: ${await res.text()}`,
      ); // some people throw the response entirely
    }

    const data = await res.json();
    return data[0];
  } catch (error) {
    if (error instanceof Error) {
      console.log(error.message);
    }
    return null;
  }
}
