import getOpenMeteo from "./getOpenMeteo";

export type FireSpotsResponseData = {
  city: string;
  count: number;
  events: {
    dist: number;
    lat: number;
    lon: number;
  }[];
  state: string;
};

export type RainfallResponseData = {
  city: string;
  clouds: number;
  lat: number;
  lon: number;
  main: {
    feels_like: number;
    grnd_level: number;
    humidity: number;
    pressure: number;
    temp: number;
  };
  rain: { "1h": number } | {};
  state: string;
  visibility: number;
  weather: {
    description: string;
    icon: string;
    main: string;
  }[];
  wind: {
    deg: number;
    gust: number;
    speed: number;
  };
};

export type LightningResponseData = {
  city: string;
  count: number;
  events: { lat: string; lon: string; dist?: number }[];
  state: string;
};

export type BrightnessResponseData = {
  city: string;
  state: string;
  temp: number;
};

/**
 * Base URL of the satellite backend that serves /fire and /lightning.
 *
 * The deployed stack lives in `satellite-fetcher-aws`. Its API Gateway id is
 * generated by AWS and is specific to the account and region it was deployed
 * into, so it changes on any redeploy elsewhere — which the project needs to do,
 * since the current deployment sits in a personal account belonging to someone
 * who has left. Keeping the id in source meant a code change and a redeploy of
 * the whole site just to point at a different backend.
 *
 * Server-side only, deliberately: every caller of this module is a server
 * component, so the value stays out of the browser bundle. Do not rename this to
 * NEXT_PUBLIC_*.
 *
 * The literal below is the endpoint in use today and exists so the site keeps
 * working in environments where the variable has not been set yet. It is a
 * migration aid, not a default worth keeping: once SATELLITE_API_URL is set in
 * Vercel for all environments, drop the fallback and let a missing value fail.
 */
const LEGACY_SATELLITE_API_URL =
  "https://7ghevyl79d.execute-api.sa-east-1.amazonaws.com/prod";

function satelliteApiUrl() {
  const configured = process.env.SATELLITE_API_URL?.trim();
  if (configured) return configured.replace(/\/+$/, "");

  console.warn(
    "[satellite] SATELLITE_API_URL não está definida — usando o endpoint legado " +
      "embutido no código. Defina a variável no ambiente para poder apontar o site " +
      "para outra conta AWS sem alterar código.",
  );
  return LEGACY_SATELLITE_API_URL;
}

/** Build the request URL for one of the satellite endpoints. */
function satelliteEndpoint(
  endpoint: string,
  lat: string,
  lon: string,
  dist?: number,
) {
  const query = new URLSearchParams({ lat, lon });
  if (dist !== undefined) query.set("dist", String(dist));
  return `${satelliteApiUrl()}/${endpoint}?${query.toString()}`;
}

/**
 * Fetch one satellite endpoint, returning `null` when the source is unavailable.
 *
 * `null` means "we do not know", and it is deliberately not zero. A backend that
 * is down used to be indistinguishable from a calm sky: this function swallowed
 * every error and returned `undefined` while its signature promised data, so
 * every caller read `.count` off nothing and quietly settled on zero. A real
 * thunderstorm and a broken deploy produced the same silence — which is fatal for
 * a project whose subject is the weather, and worse for any research done on top
 * of it, since the record cannot tell an outage from a quiet night.
 *
 * Returning `null` from a typed signature forces each caller to decide what an
 * unknown means for it. Do not "simplify" this back to `?? 0`.
 */
export default async function getData<T>(
  endpoint: string,
  lat: string,
  lon: string,
  dist?: number,
): Promise<T | null> {
  const url = satelliteEndpoint(endpoint, lat, lon, dist);

  try {
    const res = await fetch(url, { next: { revalidate: 7200 } });

    if (!res.ok) {
      // The old messages here named satellite-fetcher.up.railway.app, a backend
      // decommissioned in 2023. Reporting a URL that was never called sends
      // whoever is debugging to the wrong place.
      console.error(
        `[satellite] ${endpoint} indisponível — ${url} respondeu ${res.status} ${res.statusText}`,
      );
      return null;
    }

    return (await res.json()) as T;
  } catch (error) {
    console.error(`[satellite] ${endpoint} indisponível — ${url}`, error);
    return null;
  }
}

/** Fire spots near a point, or `null` when NASA FIRMS could not be reached. */
export async function getFireSpots(
  lat: string,
  lon: string,
  dist?: number,
): Promise<FireSpotsResponseData | null> {
  return await getData<FireSpotsResponseData>("fire", lat, lon, dist);
}

async function openWeather(
  lat: string | number,
  lon: string | number,
  lang: string,
): Promise<RainfallResponseData> {
  const part = "minutely,hourly,daily,alerts";

  try {
    const res = await fetch(
      `https://api.openweathermap.org/data/3.0/onecall?lat=${lat}&lon=${lon}&exclude=${part}&appid=${process.env.OPEN_WEATHER_API_KEY}&units=metric&lang=${lang}`,
      { next: { revalidate: 7200 } },
    );

    if (!res.ok) {
      throw new Error(
        `Response from openweather was not ok. Status: ${
          res.status
        } Message: ${await res.text()}`,
      ); // some people throw the response entirely
    }
    const data = await res.json();

    const transformedData = {
      city: "Open Weather API",
      clouds: data.current.clouds,
      lat: data.lat,
      lon: data.lon,
      main: {
        feels_like: data.current.feels_like,
        humidity: data.current.humidity,
        pressure: data.current.pressure,
        temp: data.current.temp,
        grnd_level: 0,
      },
      rain: data.current.rain ? { "1h": data.current.rain["1h"] } : {},
      state: "Open weather API",

      visibility: data.current.visibility,
      weather: data.current.weather,
      wind: {
        deg: data.current.wind_deg,
        gust: data.current.wind_gust,
        speed: data.current.wind_speed,
      },
    };
    return transformedData;
  } catch (error) {
    console.log(error);
    const transformedData = {
      city: "Open Weather API",
      clouds: 30,
      lat: 0,
      lon: 0,
      main: {
        feels_like: 24,
        humidity: 30,
        pressure: 20,
        temp: 24,
        grnd_level: 0,
      },
      rain: {},
      state: "Open weather API",

      visibility: 100,
      weather: [
        {
          description: "indisponível",
          icon: "indisponível",
          main: "indisponível",
        },
      ],
      wind: {
        deg: 90,
        gust: 40,
        speed: 30,
      },
    };
    return transformedData;
  }
}

export async function getWeather(
  lat: string | number,
  lon: string | number,
  options = { lang: "pt_br" },
): Promise<RainfallResponseData> {
  if (options && options.lang === "en") options.lang = "en_us";
  if (options && options.lang === "pt") options.lang = "pt_br";

  //this is the old fetch, using satellite-fetcher API
  //return getData("rainfall", lat, lon);
  //return openWeather(lat, lon, options.lang);
  const resp = await getOpenMeteo({ lat, lon });
  return resp;
}

/**
 * Lightning near a point, or `null` when the GOES pipeline could not be reached.
 *
 * This used to answer a failure with `{count: 1, state: "This is mock data..."}`
 * — an invented strike. That branch was in fact unreachable, because getData
 * never threw, so the real behaviour was a silent zero. Both are fabrications;
 * they merely lie in opposite directions. Neither belongs in a system whose
 * output is an artwork about real weather.
 */
export async function getLightning(
  lat: string,
  lon: string,
  dist: number,
): Promise<LightningResponseData | null> {
  return await getData<LightningResponseData>("lightning", lat, lon, dist);
}

export async function getBrightness(
  lat: string,
  lon: string,
): Promise<BrightnessResponseData | null> {
  return getData<BrightnessResponseData>("brightness", lat, lon);
}

export async function reverseGeocode(
  lat: string | number,
  lon: string | number,
): Promise<{
  name: string;
  local_name: any[];
  lat: number;
  lon: number;
  country: string;
  state?: string;
} | null> {
  const url = `http://api.openweathermap.org/geo/1.0/reverse?lat=${lat}&lon=${lon}&limit=${1}&appid=${
    process.env.OPEN_WEATHER_API_KEY
  }`;

  try {
    const res = await fetch(url);
    if (!res.ok) {
      throw new Error(
        `Response from reverse geocode was not ok. Status: ${
          res.status
        } Message: ${await res.text()}`,
      ); // some people throw the response entirely
    }

    const data = await res.json();
    return data[0];
  } catch (error) {
    if (error instanceof Error) {
      console.log(error.message);
    }
    return null;
  }
}
