/**
 * AUTOGENERATED by scripts/gen-composition-registry.mjs — do not edit by hand.
 *
 * Source of truth: compositions/<slug>/composition.json plus the sketch
 * beside it. Run `npm run compositions:codegen` after changing either.
 */

import { createComposition } from "./composition-runtime";
import type { CompositionManifest } from "./composition-runtime";

import ExemploClimaSketch from "@/compositions/exemplo-clima/sketch";

export const DECLARED_COMPOSITION_MANIFESTS = {
  exemploClima: {
    id: "exemploClima",
    label: "Exemplo — clima",
    attributes: ["temperature","rain"],
    audio: {"kind":"mp3","by":"rain","steps":[{"below":3,"file":"NRlight.mp3"},{"below":6,"file":"NRmedium.mp3"},{"file":"NRheavy.mp3"}]},
    thumb: "lluvia.png",
    author: "GaiaSenses",
  },
} as const satisfies Record<string, CompositionManifest>;

export const DECLARED_COMPOSITIONS = {
  exemploClima: createComposition(DECLARED_COMPOSITION_MANIFESTS.exemploClima, ExemploClimaSketch),
};

export type DeclaredCompositionName = keyof typeof DECLARED_COMPOSITIONS;
