/**
 * AUTOGENERATED by scripts/gen-composition-registry.mjs — do not edit by hand.
 *
 * Source of truth: lib/gaia-composition-attributes.json
 */

export const COMPOSITION_ATTRIBUTES =
  {
    "temperature": {
      "label": "Temperatura do ar",
      "unit": "°C",
      "source": "weather",
      "path": "main.temp",
      "range": [
        -60,
        55
      ]
    },
    "humidity": {
      "label": "Umidade relativa",
      "unit": "%",
      "source": "weather",
      "path": "main.humidity",
      "range": [
        0,
        100
      ]
    },
    "clouds": {
      "label": "Cobertura de nuvens",
      "unit": "%",
      "source": "weather",
      "path": "clouds",
      "range": [
        0,
        100
      ]
    },
    "rain": {
      "label": "Chuva na última hora",
      "unit": "mm/h",
      "source": "weather",
      "path": "rain.1h",
      "range": [
        0,
        100
      ]
    },
    "windSpeed": {
      "label": "Velocidade do vento",
      "unit": "m/s",
      "source": "weather",
      "path": "wind.speed",
      "range": [
        0,
        60
      ]
    },
    "windDeg": {
      "label": "Direção do vento",
      "unit": "°",
      "source": "weather",
      "path": "wind.deg",
      "range": [
        0,
        360
      ]
    },
    "lightningCount": {
      "label": "Raios detectados por perto",
      "unit": "",
      "source": "lightning",
      "path": "count",
      "range": [
        0,
        500
      ]
    },
    "fireCount": {
      "label": "Focos de queimada por perto",
      "unit": "",
      "source": "fire",
      "path": "count",
      "range": [
        0,
        500
      ]
    },
    "closeFires": {
      "label": "Focos a menos de 50 km",
      "unit": "",
      "source": "fire",
      "path": "closeCount",
      "range": [
        0,
        500
      ]
    },
    "lat": {
      "label": "Latitude do centro do mapa",
      "unit": "°",
      "source": "position",
      "path": "lat",
      "range": [
        -90,
        90
      ]
    },
    "lon": {
      "label": "Longitude do centro do mapa",
      "unit": "°",
      "source": "position",
      "path": "lon",
      "range": [
        -180,
        180
      ]
    }
  } as const;
